### ISSUE TITLE
Convert value from hex 

### ISSUE THREAD

**Issue by thirdeye-yusuf** [madisongh/keystore#2]
Hi @madisongh 

Apologies for my ignorance, so I think I've got everything configured properly and added a file and dmc pass with eksgen tool and on the jetson with the keystoretool I'm able to query these values and a hex value is returned.

I tried piping the value to `xxd -r -p` to try and convert it to ascii text but I'm not getting the expected output.

Could you please advise?

Many Thanks

**Comment by madisongh** [comment]
The passphrase returned by `keystoretool` is not the stored passphrase from the EKB, but is SHA256 hashed with the module's unique ID by the `getdmckey_handle_port()` function in the keystore TA.   So it won't translate into anything readable.

**Comment by thirdeye-yusuf** [comment]
sorry for my ignorance again, could you possibly recommend steps to get the dmc passphrase, guessing there's extra steps I'm missing

**Comment by madisongh** [comment]
If you want to get back the original plaintext you programmed into the EKB, just modify the `getdmckey_handle_port()` function in `app/keystore/keystore.c` to return it directly instead of going through the extra hashing.

**Comment by thirdeye-yusuf** [comment]
ok, will see what I can do.
Thanks for your help

**Comment by thirdeye-yusuf** [comment]
guessing I would just replace the contents of the else statement with:
`memcpy(outkey, dmcrypt_passphrase, dmcpplen)` ?

**Comment by madisongh** [comment]
Well, `outkey` is only 32 bytes in size, so it's a little more complicated than that, if the plaintext could be longer.

**Comment by thirdeye-yusuf** [comment]
thanks, I'll tweak to make sure it's no bigger than 32 bytes
